name: PR Builder

# Controls when the workflow will run
on:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  jest_coverage:
    name: UT Coverage
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      # Runs a single command using the runners shell
      - name: Jest Coverage
        run: |
          pwd
          node ./scripts/jestCoverageDiff.js
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
